### ISSUE TITLE
Template doesn't create all needed tables

### ISSUE THREAD

**Issue by rgg1993** [aws-solutions/aws-devops-monitoring-dashboard#12]
I deployed the solution on AWS Cloudformation, which turned out to be not as smooth as it seemed to be.  Issues:

- Creation of CodeBuildEventsCodeBuildKinesisFirehose and CodeCommitKinesisFirehoseToS3KinesisFirehose:
 
Since Datalake automatically adds a layer of protection on its databases and tables, one must be attentive to when the role is created to go to the Datalake console and grant it the access needed to the database created. Otherwise, on this step it will throw error: `"Access was denied when calling Glue. Please ensure that the role specified in the data format conversion configuration has the necessary permissions. Insufficient Lake Formation permission(s) on aws_codebuild_metrics_table`. Additionally, the template creates so many roles that it's hard to be sure regarding which role should be assigned the permissions. 

- The solution doesn't create the tables from which the dashboards feed themselves. 
Yeap. Once the stack was successfully deployed, the dashboards throw error:

`awsdatacatalog.aws_devops_metrics_db_so0143.code_deployment_detail_view does not exist`

Which makes sense, since when I go to the tables in databases, it shows the following two, missing aws_devops_metrics_db_so0143.code_deployment_detail_view ws_devops_metrics_db_so0143.code_build_detail_view. 

![image](https://user-images.githubusercontent.com/70332427/147975942-e35618af-4c7f-413d-842f-c7c685734db8.png)

**To Reproduce**
Deploy your stack using the cloudformation template linked 

**Expected behavior**
Tables should be created properly so dashboards can be fed.

**Please complete the following information about the solution:**

**Comment by aijunpeng** [comment]
Thanks for reporting the issue. I assume the account you deployed the solution already has lake formation configured. We are aware that if the glue legacy roles were changed in your account you may encounter the glue permission issue when deploying the solution. To fix it, you should grant IAM access for new databases and new tables in databases in lake formation (see screenshot below). Also can you elaborate the steps for "one must be attentive to when the role is created to go to the Datalake console and grant it the access needed to the database created"? Particularly what access did you grant to which role? Did it solve the problem? Screenshots would be helpful.

![image](https://user-images.githubusercontent.com/48494578/149244890-5eff76e3-f4a8-47bd-b595-e9b0c833ee04.png)

**Comment by aijunpeng** [comment]
About the missing views, the solution should create all required views once the solution is successfully deployed. Please verify if you have correctly configured QuickSight permissions: https://docs.aws.amazon.com/solutions/latest/aws-devops-monitoring-dashboard/automated-deployment.html#step-2-configure-amazon-quicksight. Furthermore, you can look into the QueryRunner Lambda logs for view creation logs or errors if something went wrong.
