### ISSUE TITLE
Support for Github workflow and actions

### ISSUE THREAD

**Issue by flochaz** [aws-solutions/aws-devops-monitoring-dashboard#16]
Is there any plan to have support for github based CI/CD (github actions, github workflow) ?

**Comment by aijunpeng** [comment]
Thanks for the request. We can add this to our roadmap. Can you please add details for your use cases?

**Comment by flochaz** [comment]
Current solution only support Code* (Pipeline/Build etc.) as source of metrics for the dashboard but for teams that use github actions as CI/CD solution nothing is pulled from the run right ?
And since the solution already have the ingestion process for pushes it could be quite easy to forward as well github pull requests and actions events.

**Comment by aijunpeng** [comment]
The solution primarily supports DevOPs metrics from AWS CI/CD pipeline using Code* services. For GitHub, we started with supporting pushes and are collecting feedbacks from customers to see what more events we can add. Are you interested in any specific GitHub actions events?

**Comment by groverlalit** [comment]
Issue resolved in past release. Closing issue.
