### ISSUE TITLE
remove the other category in the GitHub dashboards

### ISSUE THREAD

**Issue by JamieB101** [aws-solutions/aws-devops-monitoring-dashboard#34]
**Is your feature request related to a problem? Please describe.**
The 'Other' category within the GitHub dashboards is currently aggregating a large number of events, which skews the data representation on the graphs. This makes it difficult to derive meaningful insights from the visualisations since the 'Other' category dominates the scale and detail of the graph.

**Describe the feature you'd like**
An enhancement to the data visualisation tool is required, where we can either filter out or break down the 'Other' category into more specific sub-categories. This would allow for a more granular analysis and a balanced view of event.

**Additional context**
In the current graphs, the 'Other' category eclipses other data points and renders the graph less useful for analysis. A feature to adjust the scale dynamically based on selected categories or an option to exclude certain categories would be beneficial. See attached screenshot for reference.

![image](https://github.com/aws-solutions/aws-devops-monitoring-dashboard/assets/34475392/9406a114-9599-48f2-bd59-192e479e4ea4)

![image](https://github.com/aws-solutions/aws-devops-monitoring-dashboard/assets/34475392/da5cfca0-ff06-4bc8-b1de-9e48e668ae3f)

**Comment by aijunpeng** [comment]
Thanks for opening this issue. This is a display limit controlled by QuickSight service. For line chart, QS displays 25 data points for color and the rest would fall in Other category. See 1) https://docs.aws.amazon.com/quicksight/latest/user/line-charts.html; 2) https://docs.aws.amazon.com/quicksight/latest/user/working-with-visual-types.html#display-limits

I would recommend you to filter data using the provided filters including author, repository, branch, AWS account, AWS Region, tag, or time period. If you tagged your resources, you can enter the tags in the solution's cloudformation stack then the solution would only show the tagged resources by default (https://docs.aws.amazon.com/solutions/latest/devops-monitoring-dashboard-on-aws/step-2.html). You can also customize the QS analysis and publish it to a new dashboard in your account as needed.

**Comment by aijunpeng** [comment]
close the ticket due to inactivity.
